-- role
insert into "wild_snap".role (oid, role_id, role_description, menu_json, role_type, status) values ('doer-steel-role-oid','doer-steel-role-id','Doer Steel Admin','[{"title":"General","type":"header"},{"title":"Dashboard","icon":"fa fa-tachometer-alt","active":true,"link":"/guardian/dashboard"},{"title":"Profile","icon":"fas fa-user-tie","active":false,"link":"/guardian/dashboard","type":"dropdown","submenus":[{"title":"My Profile","link":"/guardian/profile"},{"title":"Change_Password","link":"/guardian/profile/change-password"}]},{"title":"Teacher","icon":"fas fa-user-tie","active":true,"link":"/guardian/teacher/list"},{"title":"Student","icon":"fas fa-user-tie","active":true,"link":"/guardian/student/list"},{"title":"Class","icon":"fas fa-chalkboard","active":false,"link":"/guardian/dashboard","type":"dropdown","submenus":[{"title":"Class Routine","link":"/guardian/class-routine/view"}]},{"title":"Notice","icon":"fa fa-clipboard-list","active":false,"type":"simple","link":"/guardian/notice/list","badge":{"text":"New Notice","class":"badge-alert","link":"/guardian/notice/list"}},{"title":"Exam","icon":"far fa-newspaper","active":false,"link":"/guardian/dashboard","type":"dropdown","submenus":[{"title":"Exam Routine","link":"/guardian/exam-routine/list"},{"title":"Exam Result","link":"/guardian/exam-result/list"}]},{"title":"Fees","icon":"fas fa-envelope-open-text","active":false,"link":"/guardian/fees","type":"dropdown","submenus":[{"title":"Due Fees","link":"/guardian/fees/due-fees/list"},{"title":"Fees Collection","link":"/guardian/fees/fees-collection/history"}]},{"title":"Attendance","icon":"far fa-users","active":false,"link":"/guardian/attendance","type":"simple"},{"title":"Home Work","icon":"fas fa-chalkboard","active":false,"link":"/guardian/home-work","type":"dropdown","submenus":[{"title":"Home Work List","link":"/guardian/home-work/list"}]}]','Admin','Active');
commit;

-- login
insert into "wild_snap".login (oid, login_id, password, user_name, name_en, name_bn, email, mobile_no, photo_path, photo_url, status, role_oid) values ('doer-steel-login-oid-0001','doer-steel-login-id-0001','$2a$10$GAgMtAzIKG2Cr/gxikpNZOmiIvBuMC0lDjvP.4607ABHz2zk6zDtW','jarifa','Doer','দুয়ার','polas.hossain@doer.com.bd','1725868816',null,null,'Active','doer-steel-role-oid');
commit;


